<?php

return [

    'groups' => [
        'content' => 'المحتوى والموقع',
        'general' => 'عام',
        'users' => 'المستخدمون',
        'academic' => 'الخطة الأكاديمية',
        'students' => 'شؤون الطلاب',
        'commerce' => 'التجارة والطلبات',
        'finance' => 'المالية',
        'crm' => 'إدارة علاقات العملاء CRM',
        'settings' => 'الإعدادات',
    ],

    'permissions' => [
        'admin.access' => ['label' => 'دخول لوحة التحكم', 'group' => 'general'],
        'dashboard.view' => ['label' => 'عرض لوحة المؤشرات', 'group' => 'general'],
        'analytics.view' => ['label' => 'عرض مؤشرات زيارات المنصة', 'group' => 'general'],
        'analytics.manage' => ['label' => 'إدارة إعدادات تحليلات المنصة', 'group' => 'settings'],
        'reports.view' => ['label' => 'عرض مركز التقارير', 'group' => 'general'],
        'reports.export' => ['label' => 'تصدير التقارير', 'group' => 'general'],

        'users.view' => ['label' => 'عرض المستخدمين', 'group' => 'users'],
        'users.manage' => ['label' => 'إنشاء وتعديل المستخدمين', 'group' => 'users'],
        'users.permissions' => ['label' => 'إدارة صلاحيات الأدوار', 'group' => 'users'],

        'students.view' => ['label' => 'عرض الطلاب', 'group' => 'students'],
        'students.manage' => ['label' => 'إدارة الطلاب', 'group' => 'students'],
        'students.impersonate' => ['label' => 'تسجيل الدخول كطالب', 'group' => 'students'],
        'requests.view' => ['label' => 'عرض طلبات الطلاب', 'group' => 'students'],
        'requests.review' => ['label' => 'مراجعة وموافقة الطلبات', 'group' => 'students'],
        'attendance.view' => ['label' => 'عرض سجلات الحضور', 'group' => 'students'],
        'attendance.manage' => ['label' => 'تسجيل وتعديل الحضور', 'group' => 'students'],
        'assignments.view' => ['label' => 'عرض الواجبات', 'group' => 'students'],
        'assignments.manage' => ['label' => 'إدارة وتقييم الواجبات', 'group' => 'students'],
        'exams.view' => ['label' => 'عرض الاختبارات والنتائج', 'group' => 'students'],
        'exams.manage' => ['label' => 'إدارة الاختبارات وبنوك الأسئلة', 'group' => 'students'],

        'programs.view' => ['label' => 'عرض البرامج', 'group' => 'academic'],
        'programs.manage' => ['label' => 'إدارة البرامج', 'group' => 'academic'],
        'courses.view' => ['label' => 'عرض المقررات', 'group' => 'academic'],
        'courses.manage' => ['label' => 'إدارة المقررات', 'group' => 'academic'],
        'batches.view' => ['label' => 'عرض الدفعات', 'group' => 'academic'],
        'batches.manage' => ['label' => 'إدارة الدفعات', 'group' => 'academic'],
        'sections.view' => ['label' => 'عرض الشعب', 'group' => 'academic'],
        'sections.manage' => ['label' => 'إدارة الشعب', 'group' => 'academic'],
        'schedules.view' => ['label' => 'عرض الجداول', 'group' => 'academic'],
        'schedules.manage' => ['label' => 'إدارة الجداول', 'group' => 'academic'],

        'orders.view' => ['label' => 'عرض الطلبات', 'group' => 'commerce'],
        'orders.manage' => ['label' => 'إدارة الطلبات', 'group' => 'commerce'],
        'catalog.view' => ['label' => 'عرض دورات الكatalog', 'group' => 'commerce'],
        'catalog.manage' => ['label' => 'إدارة محتوى دورات الكatalog', 'group' => 'commerce'],
        'support.view' => ['label' => 'عرض تذاكر الدعم', 'group' => 'commerce'],
        'support.manage' => ['label' => 'إدارة تذاكر الدعم', 'group' => 'commerce'],

        'crm.view' => ['label' => 'دخول نظام CRM وعرض العملاء المسندين', 'group' => 'crm'],
        'crm.contacts.view_all' => ['label' => 'عرض عملاء جميع موظفي السيلز', 'group' => 'crm'],
        'crm.contacts.create' => ['label' => 'إضافة عميل جديد', 'group' => 'crm'],
        'crm.contacts.update' => ['label' => 'تعديل بيانات العميل', 'group' => 'crm'],
        'crm.contacts.delete' => ['label' => 'حذف عميل من CRM', 'group' => 'crm'],
        'crm.contacts.change_status' => ['label' => 'تغيير حالة العميل', 'group' => 'crm'],
        'crm.contacts.export' => ['label' => 'تصدير قائمة العملاء', 'group' => 'crm'],
        'crm.activities.log' => ['label' => 'تسجيل التواصل والمتابعة', 'group' => 'crm'],
        'crm.assign' => ['label' => 'توزيع وإعادة توزيع العملاء', 'group' => 'crm'],
        'crm.assign.bulk' => ['label' => 'التوزيع الجماعي للعملاء', 'group' => 'crm'],
        'crm.import' => ['label' => 'استيراد ملفات العملاء', 'group' => 'crm'],
        'crm.sync' => ['label' => 'مزامنة المسجلين وطلبات التسجيل', 'group' => 'crm'],
        'crm.rules.view' => ['label' => 'عرض قواعد توزيع السيلز', 'group' => 'crm'],
        'crm.rules.manage' => ['label' => 'إدارة قواعد توزيع السيلز حسب البرنامج', 'group' => 'crm'],
        'crm.settings.view' => ['label' => 'عرض إعدادات الحالات والمصادر', 'group' => 'crm'],
        'crm.statuses.manage' => ['label' => 'إدارة حالات مسار المبيعات', 'group' => 'crm'],
        'crm.sources.manage' => ['label' => 'إدارة مصادر العملاء', 'group' => 'crm'],
        'crm.audit.view' => ['label' => 'عرض سجل أحداث CRM', 'group' => 'crm'],

        'finance.view' => ['label' => 'التحليلات المالية', 'group' => 'finance'],
        'installments.view' => ['label' => 'عرض التقسيط والعقود', 'group' => 'finance'],
        'installments.manage' => ['label' => 'إدارة خطط وعقود التقسيط', 'group' => 'finance'],
        'payment-settings.manage' => ['label' => 'إعدادات الدفع', 'group' => 'finance'],
        'teams-settings.manage' => ['label' => 'إعدادات Microsoft Teams', 'group' => 'settings'],
        'zoom-settings.manage' => ['label' => 'إعدادات وربط Zoom', 'group' => 'settings'],
        'zoxagent-settings.manage' => ['label' => 'إعدادات وربط ZoxAgent Meet', 'group' => 'settings'],
        'notifications.manage' => ['label' => 'الإشعارات وقواعدها', 'group' => 'settings'],
        'staff.view' => ['label' => 'عرض الكوادر الأكاديمية', 'group' => 'academic'],
        'staff.manage' => ['label' => 'إدارة الكوادر الأكاديمية', 'group' => 'academic'],
        'staff.impersonate' => ['label' => 'تسجيل الدخول المباشر كمدرب', 'group' => 'academic'],

        'settings.view' => ['label' => 'عرض إعدادات المنصة', 'group' => 'settings'],
        'settings.manage' => ['label' => 'تعديل إعدادات المنصة', 'group' => 'settings'],
        'system-settings.view' => ['label' => 'عرض مركز إعدادات النظام', 'group' => 'settings'],
        'system-settings.manage' => ['label' => 'إدارة إعدادات التطبيق', 'group' => 'settings'],
        'mail-settings.manage' => ['label' => 'إعدادات البريد الإلكتروني', 'group' => 'settings'],
        'infrastructure-settings.manage' => ['label' => 'إعدادات البنية التحتية', 'group' => 'settings'],
        'storage-settings.manage' => ['label' => 'إعدادات التخزين والسحابة', 'group' => 'settings'],
        'certificates.view' => ['label' => 'عرض الشهادات', 'group' => 'students'],
        'certificates.manage' => ['label' => 'إصدار وإدارة الشهادات', 'group' => 'students'],
        'certificate-templates.manage' => ['label' => 'تصميم وإدارة قوالب الشهادات', 'group' => 'students'],
        'statements.view' => ['label' => 'عرض طلبات الإفادات', 'group' => 'students'],
        'statements.manage' => ['label' => 'إصدار الإفادات', 'group' => 'students'],
        'refunds.view' => ['label' => 'عرض طلبات الاسترداد', 'group' => 'commerce'],
        'refunds.manage' => ['label' => 'معالجة طلبات الاسترداد', 'group' => 'commerce'],
        'audit-log.view' => ['label' => 'عرض سجل التدقيق', 'group' => 'settings'],

        'pages.view' => ['label' => 'عرض صفحات الموقع', 'group' => 'content'],
        'pages.manage' => ['label' => 'إدارة صفحات الموقع', 'group' => 'content'],
        'media.view' => ['label' => 'عرض مكتبة الوسائط', 'group' => 'content'],
        'media.manage' => ['label' => 'إدارة مكتبة الوسائط', 'group' => 'content'],
        'articles.view' => ['label' => 'عرض الأخبار والفعاليات', 'group' => 'content'],
        'articles.manage' => ['label' => 'إدارة الأخبار والفعاليات', 'group' => 'content'],
        'menus.view' => ['label' => 'عرض قوائم التنقل', 'group' => 'content'],
        'menus.manage' => ['label' => 'إدارة قوائم التنقل', 'group' => 'content'],

        'applications.view' => ['label' => 'عرض طلبات التسجيل', 'group' => 'students'],
        'applications.review' => ['label' => 'مراجعة طلبات التسجيل', 'group' => 'students'],
    ],

    'role_defaults' => [
        'admin' => ['*'],
        'sales' => [
            'admin.access',
            'crm.view',
            'crm.contacts.update',
            'crm.contacts.change_status',
            'crm.activities.log',
        ],
        'staff' => [
            'admin.access',
            'dashboard.view',
            'reports.view',
            'reports.export',
            'students.view',
            'students.manage',
            'requests.view',
            'requests.review',
            'applications.view',
            'applications.review',
            'attendance.view',
            'attendance.manage',
            'assignments.view',
            'assignments.manage',
            'exams.view',
            'exams.manage',
            'certificates.view',
            'statements.view',
            'programs.view',
            'courses.view',
            'batches.view',
            'batches.manage',
            'sections.view',
            'schedules.view',
            'schedules.manage',
            'staff.view',
            'orders.view',
            'refunds.view',
        ],
        'student' => [],
    ],

];
