<?php

return [
    'admin.platform-analytics' => 'analytics.view',
    'admin.crm' => 'crm.view',
    'admin.crm.contacts.show' => 'crm.view',
    'admin.crm.import' => 'crm.import',
    'admin.crm.rules' => ['crm.rules.view', 'crm.rules.manage'],
    'admin.crm.settings' => ['crm.settings.view', 'crm.statuses.manage', 'crm.sources.manage'],
    'admin.crm.audit' => ['crm.audit.view', 'audit-log.view'],

    /*
    |--------------------------------------------------------------------------
    | Admin route → permission
    |--------------------------------------------------------------------------
    | Each named admin route requires the listed permission.
    | Unlisted routes fall back to admin.access only.
    */

    'admin.dashboard' => 'dashboard.view',
    'admin.reports' => 'reports.view',
    'admin.logout' => 'admin.access',

    'admin.financial' => 'finance.view',
    'admin.installment-plans' => 'installments.view',
    'admin.installment-plans.create' => 'installments.manage',
    'admin.installment-plans.edit' => 'installments.manage',
    'admin.installment-contracts' => 'installments.view',
    'admin.installment-contracts.show' => 'installments.view',
    'admin.installment-reports' => 'installments.view',
    'admin.installment-settings' => 'installments.manage',
    'admin.installment-dunning' => 'installments.manage',
    'admin.cms-pages' => 'pages.view',
    'admin.cms-pages.create' => 'pages.manage',
    'admin.cms-pages.edit' => 'pages.manage',
    'admin.cms-pages.preview' => 'pages.view',
    'admin.media-library' => 'media.view',
    'admin.cms-menus' => 'menus.view',
    'admin.articles' => 'articles.view',
    'admin.articles.create' => 'articles.manage',
    'admin.articles.edit' => 'articles.manage',
    'admin.articles.media' => 'articles.manage',
    'admin.article-categories' => 'articles.view',
    'admin.enrollment' => 'students.view',
    'admin.graduates' => 'students.view',
    'admin.staff' => 'staff.view',
    'admin.staff.members' => 'staff.view',
    'admin.staff.create' => 'staff.manage',
    'admin.staff.edit' => 'staff.manage',
    'admin.staff.show' => 'staff.view',
    'admin.staff.impersonate' => 'staff.impersonate',
    'admin.staff.impersonate.stop' => 'staff.impersonate',

    'admin.support-tickets' => 'support.view',
    'admin.support-tickets.show' => 'support.view',

    'admin.orders' => 'orders.view',
    'admin.orders.show' => 'orders.view',
    'admin.catalog-courses' => 'catalog.view',
    'admin.catalog-courses.create' => 'catalog.manage',
    'admin.catalog-courses.edit' => 'catalog.manage',
    'admin.catalog-courses.content' => 'catalog.manage',
    'admin.catalog-courses.lesson-file' => 'catalog.manage',
    'admin.catalog-courses.module-image' => 'catalog.view',
    'admin.settings' => 'settings.view',
    'admin.system-settings' => 'system-settings.view',
    'admin.system-settings.section' => 'system-settings.view',
    'admin.payment-settings' => 'payment-settings.manage',
    'admin.teams-settings' => 'teams-settings.manage',
    'admin.zoom-settings' => 'zoom-settings.manage',
    'admin.notifications' => 'notifications.manage',
    'admin.notification-rules' => 'notifications.manage',
    'admin.audit-log' => 'audit-log.view',
    'admin.refunds' => 'refunds.view',
    'admin.certificates' => 'certificates.view',
    'admin.certificates.download' => 'certificates.view',
    'admin.certificate-templates' => 'certificate-templates.manage',
    'admin.certificate-templates.builder' => 'certificate-templates.manage',
    'admin.statements' => 'statements.view',
    'admin.sessions' => 'sections.view',
    'admin.assignments' => 'assignments.view',
    'admin.assignments.create' => 'assignments.manage',
    'admin.assignments.edit' => 'assignments.manage',
    'admin.assignments.show' => 'assignments.view',
    'admin.exams' => 'exams.view',
    'admin.exams.create' => 'exams.manage',
    'admin.exams.edit' => 'exams.manage',
    'admin.exams.builder' => 'exams.manage',
    'admin.exams.preview' => 'exams.manage',
    'admin.exams.integrity' => 'exams.manage',

    'admin.users' => 'users.view',
    'admin.users.permissions' => 'users.permissions',
    'admin.users.create' => 'users.manage',
    'admin.users.access' => 'users.permissions',
    'admin.users.edit' => 'users.manage',
    'admin.users.show' => 'users.view',

    'admin.programs' => 'programs.view',
    'admin.programs.create' => 'programs.manage',
    'admin.programs.edit' => 'programs.manage',
    'admin.programs.show' => 'programs.view',

    'admin.batches' => 'batches.view',
    'admin.batches.create' => 'batches.manage',
    'admin.batches.edit' => 'batches.manage',
    'admin.batches.show' => 'batches.view',

    'admin.students' => 'students.view',
    'admin.students.create' => 'students.manage',
    'admin.students.edit' => 'students.manage',
    'admin.students.show' => 'students.view',
    'admin.students.impersonate' => 'students.impersonate',
    'admin.students.impersonate.stop' => 'students.impersonate',

    'admin.sections' => 'sections.view',
    'admin.sections.create' => 'sections.manage',
    'admin.sections.edit' => 'sections.manage',
    'admin.sections.show' => 'sections.view',

    'admin.schedules' => 'schedules.view',

    'admin.levels' => 'courses.view',
    'admin.levels.create' => 'courses.manage',
    'admin.levels.edit' => 'courses.manage',

    'admin.academic-courses' => 'courses.view',
    'admin.academic-courses.create' => 'courses.manage',
    'admin.academic-courses.edit' => 'courses.manage',
    'admin.academic-courses.show' => 'courses.view',

    'admin.requests.deferral' => 'requests.view',
    'admin.requests.withdrawal' => 'requests.view',
    'admin.requests.program-change' => 'requests.view',
    'admin.requests.semester-excuse' => 'requests.view',
    'admin.requests.show' => 'requests.view',

    'admin.applications.client' => 'applications.view',
    'admin.applications.company' => 'applications.view',
    'admin.applications.marketer' => 'applications.view',
    'admin.applications.instructor' => 'applications.view',
    'admin.applications.employee' => 'applications.view',
    'admin.applications.job-seeker' => 'applications.view',
    'admin.applications.cooperative' => 'applications.view',
    'admin.applications.fellowship' => 'applications.view',
    'admin.fellowships' => 'applications.view',
    'admin.fellowships.edit' => 'applications.review',
    'admin.fellowships.form-fields' => 'applications.review',
    'admin.fellowships.settings' => 'applications.review',
    'admin.applications.show' => 'applications.view',
    'admin.applications.attachment' => 'applications.view',

];
