<?php

return [
    'base_url' => env('ZOOM_BASE_URL', 'https://api.zoom.us/v2'),
    'oauth_url' => env('ZOOM_OAUTH_URL', 'https://zoom.us/oauth/token'),
    'enabled' => env('ZOOM_ENABLED', false),
    'account_id' => env('ZOOM_ACCOUNT_ID'),
    'client_id' => env('ZOOM_CLIENT_ID'),
    'client_secret' => env('ZOOM_CLIENT_SECRET'),
    'webhook_secret' => env('ZOOM_WEBHOOK_SECRET'),
    'default_host' => env('ZOOM_DEFAULT_HOST'),
    'host_strategy' => env('ZOOM_HOST_STRATEGY', 'central'),
    'auto_attendance' => env('ZOOM_AUTO_ATTENDANCE', true),
    'sync_interval' => env('ZOOM_SYNC_INTERVAL', 15),
    'late_minutes' => env('ZOOM_LATE_MINUTES', 10),
    'minimum_attendance_percent' => env('ZOOM_MINIMUM_ATTENDANCE_PERCENT', 0),
    'minimum_attendance_minutes' => env('ZOOM_MINIMUM_ATTENDANCE_MINUTES', 1),
    'registration_required' => env('ZOOM_REGISTRATION_REQUIRED', true),
    'waiting_room' => env('ZOOM_WAITING_ROOM', true),
    'host_video' => env('ZOOM_HOST_VIDEO', true),
    'participant_video' => env('ZOOM_PARTICIPANT_VIDEO', false),
    'mute_upon_entry' => env('ZOOM_MUTE_UPON_ENTRY', true),
    'join_before_host' => env('ZOOM_JOIN_BEFORE_HOST', false),
    'allow_multiple_devices' => env('ZOOM_ALLOW_MULTIPLE_DEVICES', false),
    'audio_mode' => env('ZOOM_AUDIO_MODE', 'both'),
    'join_window_minutes' => env('ZOOM_JOIN_WINDOW_MINUTES', 30),
    'recording_policy' => env('ZOOM_RECORDING_POLICY', 'automatic'),
    'recording_destination' => env('ZOOM_RECORDING_DESTINATION', 'zoom'),
    's3_disk' => env('ZOOM_S3_DISK', 's3'),
    'google_disk' => env('ZOOM_GOOGLE_DISK', 'google'),
    'token_safety_seconds' => 120,
    'webhook_tolerance_seconds' => 300,
];
